[project]
name = "neural-networks-project-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "box2d>=2.3.10",
  "gymnasium>=1.3.0",
  "pygame>=2.6.1",
  "swig>=4.4.1",
  "torch>=2.12.0",
  "tqdm>=4.67.3",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
  { index = "pytorch-cu130", marker = "sys_platform != 'darwin'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
  { index = "pytorch-cu130", marker = "sys_platform != 'darwin'" },
]

[tool.ruff]
line-length = 88
target-version = "py313"

# Enable basic checks and import sorting
lint.select = [
  "E",   # All errors
  "F",   # All pyflakes checks (including unused imports)
  "I",   # Import sorting checks
  "B",   # All flake8-bugbear checks
  "ANN", # All flake8-annotations checks
]

# Ignore line length violations.
lint.ignore = ["E501"]

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Allow unused imports in __init__.py files.
"__init__.py" = ["F401"]

[dependency-groups]
dev = ["ipykernel>=7.2.0", "pyright>=1.1.408", "ruff>=0.15.5"]

[tool.pyright]
venvPath = "./.venv"
typeCheckingMode = "standard"
exclude = ["**/__pycache__", ".*", "**/.ipynb_checkpoints**"]
include = [""]
pythonPlatform = "All"
pythonVersion = "3.13"
